[package]
name = "papucoin-core"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
blake2 = "0.11.0"
digest = { version = "0.11", default-features = false, features = ["alloc"] }
ed25519-dalek = { version = "3.0.0", default-features = false }
elliptic-curve = { version = "0.14.1", default-features = false, features = ["sec1", "arithmetic"] }
serde = { version = "1.0.229", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.151", default-features = false, features = ["alloc"] }
